import { useState, useEffect, useCallback } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { useDebouncedCallback } from "@/hooks/useDebounce";
import { useAsyncOperation } from "@/hooks/useAsyncOperation";
import PredictiveAnalytics from "@/components/ai/PredictiveAnalytics";
import CompetitorAnalysisDashboard from "@/components/analytics/CompetitorAnalysisDashboard";
import MonetizationStrategy from "@/components/analytics/MonetizationStrategy";
import { AdvancedAnalytics } from "@/components/analytics/AdvancedAnalytics";
import { AnalyticsDashboard } from "@/components/analytics/AnalyticsDashboard";
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarInset,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarHeader,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { BarChart3, TrendingUp, Eye, Users, DollarSign, Heart, Youtube, Instagram, Facebook, Brain, Search, Target, Download, FileText, FileSpreadsheet, Activity } from "lucide-react";

export default function Analytics() {
  const { toast } = useToast();
  const [timeRange, setTimeRange] = useState("7d");
  const [platforms, setPlatforms] = useState<string[]>(["all"]);
  const [selectedContentId, setSelectedContentId] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState<"dashboard" | "predictive" | "competitor" | "monetization" | "traditional" | "advanced">("dashboard");

  // Async operations for export functions
  const { execute: executeExportCSV, isLoading: isExportingCSV } = useAsyncOperation(
    async () => {
      const csvData = [
        ['Content Title', 'Platform', 'Views', 'Engagement', 'Created Date', 'Status'],
        ...filteredContent.map((item: any) => [
          item.title || '',
          item.platform || '',
          item.views || 0,
          item.engagement || 0,
          new Date(item.createdAt).toLocaleDateString(),
          item.status || ''
        ])
      ];

      const csvContent = csvData.map(row => row.join(',')).join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `analytics-export-${new Date().toISOString().split('T')[0]}.csv`;
      link.click();
      URL.revokeObjectURL(link.href);
    },
    {
      successMessage: 'CSV export completed successfully',
      errorMessage: 'Failed to export CSV. Please try again.',
    }
  );

  const { execute: executeExportJSON, isLoading: isExportingJSON } = useAsyncOperation(
    async () => {
      const exportData = {
        exportDate: new Date().toISOString(),
        timeRange,
        platforms,
        metrics: metricsData,
        content: filteredContent,
        summary: {
          totalViews: metricsData?.totalViews || 0,
          totalSubscribers: metricsData?.totalSubscribers || 0,
          avgEngagement: metricsData?.avgEngagement || 0,
          totalRevenue: metricsData?.totalRevenue || 0
        }
      };

      const jsonContent = JSON.stringify(exportData, null, 2);
      const blob = new Blob([jsonContent], { type: 'application/json;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `analytics-export-${new Date().toISOString().split('T')[0]}.json`;
      link.click();
      URL.revokeObjectURL(link.href);
    },
    {
      successMessage: 'JSON export completed successfully',
      errorMessage: 'Failed to export JSON. Please try again.',
    }
  );

  const { execute: executeGenerateReport, isLoading: isGeneratingReport } = useAsyncOperation(
    async () => {
      const reportContent = `
Analytics Report - ${new Date().toLocaleDateString()}
Time Range: ${timeRange}
Platforms: ${platforms.join(', ')}

Summary Metrics:
- Total Views: ${formatNumber(metricsData?.totalViews || 0)}
- Subscribers: ${formatNumber(metricsData?.totalSubscribers || 0)}
- Engagement Rate: ${(metricsData?.avgEngagement || 0).toFixed(1)}%
- Revenue: ${formatNumber(metricsData?.totalRevenue || 0)}

Content Performance:
${filteredContent.map((item: any, index: number) =>
  `${index + 1}. ${item.title} (${item.platform})
     - Views: ${formatNumber(item.views || 0)}
     - Engagement: ${(item.engagement || 0).toFixed(1)}%
     - Date: ${new Date(item.createdAt).toLocaleDateString()}\n`
).join('')}

Generated by Renexus Analytics - ${new Date().toISOString()}
      `.trim();

      const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `analytics-report-${new Date().toISOString().split('T')[0]}.txt`;
      link.click();
      URL.revokeObjectURL(link.href);
    },
    {
      successMessage: 'Report generated successfully',
      errorMessage: 'Failed to generate report. Please try again.',
    }
  );

  // Debounced functions
  const debouncedTimeRangeChange = useDebouncedCallback((range: string) => {
    setTimeRange(range);
  }, 300);

  const debouncedSectionChange = useDebouncedCallback((section: typeof activeSection) => {
    setActiveSection(section);
  }, 200);

  // Handle URL parameters for specific content analytics
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const contentId = urlParams.get('content');
    if (contentId) {
      setSelectedContentId(contentId);
    }
  }, []);

  const { data: metrics } = useQuery({
    queryKey: ['/api/dashboard/metrics'],
    retry: false,
  });

  const { data: content } = useQuery({
    queryKey: ['/api/content'],
    retry: false,
  });

  const metricsData: any = metrics || {};
  const contentList: any[] = Array.isArray(content) ? content : (Array.isArray((content as any)?.content) ? (content as any).content : []);

  const getPlatformIcon = (platform: string) => {
    switch (platform.toLowerCase()) {
      case 'youtube':
        return <Youtube className="w-5 h-5 text-red-600" />;
      case 'instagram':
        return <Instagram className="w-5 h-5 text-pink-600" />;
      case 'facebook':
        return <Facebook className="w-5 h-5 text-blue-600" />;
      default:
        return <BarChart3 className="w-5 h-5 text-gray-600" />;
    }
  };

  const formatNumber = (num: number) => {
    if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
    if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
    return num.toString();
  };

  const PLATFORM_OPTIONS = [
    { value: "all", label: "All" },
    { value: "youtube", label: "YouTube" },
    { value: "instagram", label: "Instagram" },
    { value: "tiktok", label: "TikTok" },
  ];

  const togglePlatform = useCallback((value: string) => {
    setPlatforms((prev) => {
      if (value === 'all') return ['all'];
      const next = prev.includes(value)
        ? prev.filter((v) => v !== value)
        : [...prev.filter((v) => v !== 'all'), value];
      return next.length === 0 ? ['all'] : next;
    });
  }, []);

  const filteredContent = contentList.filter((item: any) =>
    platforms.includes('all') ? true : platforms.includes(item.platform)
  );

  // Export functions
  const exportToCSV = () => {
    const csvData = [
      ['Content Title', 'Platform', 'Views', 'Engagement', 'Created Date', 'Status'],
      ...filteredContent.map((item: any) => [
        item.title || '',
        item.platform || '',
        item.views || 0,
        item.engagement || 0,
        new Date(item.createdAt).toLocaleDateString(),
        item.status || ''
      ])
    ];

    const csvContent = csvData.map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `analytics-export-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  const exportToJSON = () => {
    const exportData = {
      exportDate: new Date().toISOString(),
      timeRange,
      platforms,
      metrics: metricsData,
      content: filteredContent,
      summary: {
        totalViews: metricsData?.totalViews || 0,
        totalSubscribers: metricsData?.totalSubscribers || 0,
        avgEngagement: metricsData?.avgEngagement || 0,
        totalRevenue: metricsData?.totalRevenue || 0
      }
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `analytics-export-${new Date().toISOString().split('T')[0]}.json`;
    link.click();
  };

  const generateReport = () => {
    const reportContent = `
Analytics Report - ${new Date().toLocaleDateString()}
Time Range: ${timeRange}
Platforms: ${platforms.join(', ')}

Summary Metrics:
- Total Views: ${formatNumber(metricsData?.totalViews || 0)}
- Subscribers: ${formatNumber(metricsData?.totalSubscribers || 0)}
- Engagement Rate: ${(metricsData?.avgEngagement || 0).toFixed(1)}%
- Revenue: $${formatNumber(metricsData?.totalRevenue || 0)}

Content Performance:
${filteredContent.map((item: any, index: number) =>
  `${index + 1}. ${item.title} (${item.platform})
     - Views: ${formatNumber(item.views || 0)}
     - Engagement: ${(item.engagement || 0).toFixed(1)}%
     - Date: ${new Date(item.createdAt).toLocaleDateString()}\n`
).join('')}

Generated by Renexus Analytics - ${new Date().toISOString()}
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `analytics-report-${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
  };

  return (
    <SidebarProvider>
      <Sidebar collapsible="icon">
        <SidebarHeader className="px-3 py-4">
          <div className="text-sm font-semibold">Analytics</div>
        </SidebarHeader>
        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupLabel>Sections</SidebarGroupLabel>
            <SidebarMenu>
              {[
                { key: "dashboard", icon: <Activity className="w-4 h-4" />, label: "Dashboard" },
                { key: "predictive", icon: <Brain className="w-4 h-4" />, label: "Predictive AI" },
                { key: "advanced", icon: <BarChart3 className="w-4 h-4" />, label: "Advanced Analytics" },
                { key: "competitor", icon: <Search className="w-4 h-4" />, label: "Competitor Intel" },
                { key: "monetization", icon: <Target className="w-4 h-4" />, label: "Monetization" },
                { key: "traditional", icon: <BarChart3 className="w-4 h-4" />, label: "Traditional" },
              ].map((item) => (
                <SidebarMenuItem key={item.key}>
                  <SidebarMenuButton 
                    isActive={activeSection === (item.key as any)} 
                    onClick={() => debouncedSectionChange(item.key as any)}
                    aria-label={`Switch to ${item.label} section`}
                  >
                    {item.icon}
                    <span>{item.label}</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>
          </SidebarGroup>
        </SidebarContent>
      </Sidebar>
      <SidebarInset>
        <div className="container mx-auto p-6 space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                Advanced Analytics
              </h1>
              <p className="text-gray-600 mt-1">AI-powered insights and predictive intelligence</p>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="flex space-x-3">
                {[
                  { key: "7d", label: "7d" },
                  { key: "30d", label: "30d" },
                  { key: "90d", label: "90d" },
                  { key: "1y", label: "1y" },
                ].map((r) => (
                  <Button 
                    key={r.key} 
                    size="sm" 
                    variant={timeRange === r.key ? "default" : "outline"} 
                    onClick={() => debouncedTimeRangeChange(r.key)}
                    aria-label={`Set time range to ${r.label}`}
                  >
                    {r.label}
                  </Button>
                ))}
              </div>
              <div className="flex flex-wrap gap-3">
                {PLATFORM_OPTIONS.map((p) => (
                  <label key={p.value} className="flex items-center gap-2 text-sm">
                    <Checkbox
                      checked={platforms.includes(p.value)}
                      onCheckedChange={() => togglePlatform(p.value)}
                    />
                    {p.label}
                  </label>
                ))}
              </div>
              <div className="flex space-x-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={executeExportCSV}
                  disabled={isExportingCSV}
                  className="flex items-center space-x-1"
                  aria-label="Export data as CSV"
                >
                  <FileSpreadsheet className="w-4 h-4" />
                  <span>{isExportingCSV ? 'Exporting...' : 'CSV'}</span>
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={executeExportJSON}
                  disabled={isExportingJSON}
                  className="flex items-center space-x-1"
                  aria-label="Export data as JSON"
                >
                  <FileText className="w-4 h-4" />
                  <span>{isExportingJSON ? 'Exporting...' : 'JSON'}</span>
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={executeGenerateReport}
                  disabled={isGeneratingReport}
                  className="flex items-center space-x-1"
                  aria-label="Generate analytics report"
                >
                  <Download className="w-4 h-4" />
                  <span>{isGeneratingReport ? 'Generating...' : 'Report'}</span>
                </Button>
              </div>
              <SidebarTrigger />
            </div>
          </div>

          {/* Overview Metrics */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card className="border border-blue-200">
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <Eye className="w-8 h-8 text-blue-600" />
              <div>
                <p className="text-sm font-medium text-gray-600">Total Views</p>
                <p className="text-2xl font-bold text-gray-900">
                   {formatNumber(metricsData?.totalViews || 0)}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border border-green-200">
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <Users className="w-8 h-8 text-green-600" />
              <div>
                <p className="text-sm font-medium text-gray-600">Subscribers</p>
                <p className="text-2xl font-bold text-gray-900">
                   {formatNumber(metricsData?.totalSubscribers || 0)}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border border-purple-200">
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <Heart className="w-8 h-8 text-purple-600" />
              <div>
                <p className="text-sm font-medium text-gray-600">Engagement</p>
                <p className="text-2xl font-bold text-gray-900">
                  {(metricsData?.avgEngagement || 0).toFixed(1)}%
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border border-orange-200">
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <DollarSign className="w-8 h-8 text-orange-600" />
              <div>
                <p className="text-sm font-medium text-gray-600">Revenue</p>
                <p className="text-2xl font-bold text-gray-900">
                  ${formatNumber(metricsData?.totalRevenue || 0)}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

          <AnimatePresence mode="wait">
            {activeSection === "dashboard" && (
              <motion.div key="dashboard" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
                <AnalyticsDashboard />
              </motion.div>
            )}

            {activeSection === "predictive" && (
              <motion.div key="predictive" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
                <PredictiveAnalytics />
              </motion.div>
            )}

            {activeSection === "advanced" && (
              <motion.div key="advanced" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
                <AdvancedAnalytics />
              </motion.div>
            )}

            {activeSection === "competitor" && (
              <motion.div key="competitor" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
                <CompetitorAnalysisDashboard />
              </motion.div>
            )}

            {activeSection === "monetization" && (
              <motion.div key="monetization" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
                <MonetizationStrategy />
              </motion.div>
            )}

                {activeSection === "traditional" && (
              <motion.div key="traditional" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="space-y-6">
          {/* Performance Trends */}
          <Card className="border border-gray-200">
            <CardHeader>
              <CardTitle className="flex items-center text-gray-900">
                <TrendingUp className="w-5 h-5 mr-2 text-blue-600" />
                Performance Trends ({timeRange})
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-64 flex items-center justify-center text-gray-500">
                Analytics chart would be displayed here based on real data
              </div>
            </CardContent>
          </Card>

          {/* Recent Content Performance */}
          <Card className="border border-gray-200">
            <CardHeader>
              <CardTitle className="flex items-center text-gray-900">
                <BarChart3 className="w-5 h-5 mr-2 text-green-600" />
                Recent Content Performance
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {filteredContent.slice(0, 5).map((item: any, index: number) => (
                  <div key={index} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                    <div className="flex items-center space-x-3">
                      {getPlatformIcon(item.platform)}
                      <div>
                        <p className="font-medium text-gray-900">{item.title}</p>
                        <p className="text-sm text-gray-600">
                          {new Date(item.createdAt).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="font-medium text-gray-900">
                        {formatNumber(item.views || 0)} views
                      </p>
                      <Badge className="bg-blue-100 text-blue-800">
                        {(item.engagement || 0).toFixed(1)}% engagement
                      </Badge>
                    </div>
                  </div>
                ))}
                
                {(!filteredContent || filteredContent.length === 0) && (
                  <div className="text-center py-8 text-gray-500">
                    <BarChart3 className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                    <p>No content data available yet</p>
                    <p className="text-sm">Create some content to see analytics</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Platform Distribution */}
          <Card className="border border-gray-200">
            <CardHeader>
              <CardTitle className="flex items-center text-gray-900">
                <Users className="w-5 h-5 mr-2 text-purple-600" />
                Platform Distribution
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-3 bg-red-50 rounded-lg">
                  <div className="flex items-center space-x-2">
                    <Youtube className="w-5 h-5 text-red-600" />
                    <span className="font-medium">YouTube</span>
                  </div>
                  <Badge className="bg-red-100 text-red-800">65%</Badge>
                </div>
                
                <div className="flex items-center justify-between p-3 bg-pink-50 rounded-lg">
                  <div className="flex items-center space-x-2">
                    <Instagram className="w-5 h-5 text-pink-600" />
                    <span className="font-medium">Instagram</span>
                  </div>
                  <Badge className="bg-pink-100 text-pink-800">25%</Badge>
                </div>
                
                <div className="flex items-center justify-between p-3 bg-blue-50 rounded-lg">
                  <div className="flex items-center space-x-2">
                    <Facebook className="w-5 h-5 text-blue-600" />
                    <span className="font-medium">TikTok</span>
                  </div>
                  <Badge className="bg-blue-100 text-blue-800">10%</Badge>
                </div>
              </div>
            </CardContent>
          </Card>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}