name: Security - OWASP ZAP DAST (Smoke)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Start app
        run: npm run perf:server:prod &

      - name: Wait for app
        run: |
          npx wait-on -t 60000 http://localhost:5000/api/health || (echo "App not up" && exit 1)

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -m 5'
      
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: zap-baseline-report.*

